include $(ROOTDIR)/rules.mk

PKG_NAME:=ipt2socks
PKG_VERSION:=1.1.3

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/zfl9/ipt2socks/tar.gz/v$(PKG_VERSION)?
PKG_HASH:=5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7

include $(INCLUDE_DIR)/package.mk

$(eval $(call BuildPackage,ipt2socks))

romfs:
	$(INSTALL_DIR) $(ROMFSDIR)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/ipt2socks $(ROMFSDIR)/usr/bin/ipt2socks
