TOPDIR=$(ROOTDIR)

DL_DIR=$(TOPDIR)/download
INCLUDE_DIR:=$(TOPDIR)/include
SCRIPT_DIR=$(TOPDIR)/tools
BUILD_DIR=$(TOPDIR)/build
STAGING_DIR=$(STAGEDIR)
TOOLCHAIN_DIR=$(CONFIG_CROSS_COMPILER_ROOT)
PKG_CONFIG_LIBDIR=$(STAGING_DIR)/lib/pkgconfig:$(STAGING_DIR)/share/pkgconfig

export TOPDIR PKG_CONFIG_LIBDIR

CP:=cp -fpR
LN:=ln -sf
FIND:=find
PATCH:=patch
SED:=sed -i -e
TAR:=tar
XARGS:=xargs -r

INSTALL_BIN:=install -m0755
INSTALL_SUID:=install -m4755
INSTALL_DIR:=install -d -m0755
INSTALL_DATA:=install -m0644
INSTALL_CONF:=install -m0600

GNU_TARGET_NAME=$(HOST_TARGET)
GNU_HOST_NAME=$(HOST_BUILD)

TARGET_CROSS:=$(CROSS_COMPILE)

TARGET_CFLAGS:=$(CFLAGS)
TARGET_CXXFLAGS:=$(CXXFLAGS)
TARGET_LDFLAGS:=$(LDFLAGS)

TARGET_LINKER?=bfd
TARGET_LDFLAGS+= -fuse-ld=$(TARGET_LINKER)
TARGET_ASFLAGS = $(TARGET_CFLAGS)

TARGET_AR:=$(TARGET_CROSS)gcc-ar
TARGET_RANLIB:=$(TARGET_CROSS)gcc-ranlib
TARGET_NM:=$(TARGET_CROSS)gcc-nm
TARGET_CC:=$(TARGET_CROSS)gcc
TARGET_CXX:=$(TARGET_CROSS)g++
TARGET_LD:=$(TARGET_CROSS)ld.$(TARGET_LINKER)

TARGET_CC_NOCACHE:=$(TARGET_CC)
TARGET_CXX_NOCACHE:=$(TARGET_CXX)

ifneq ($(CONFIG_CCACHE),)
  TARGET_CC:= ccache $(TARGET_CC)
  TARGET_CXX:= ccache $(TARGET_CXX)
  export CCACHE_BASEDIR:=$(TOPDIR)
  export CCACHE_DIR:=$(if $(call qstrip,$(CONFIG_CCACHE_DIR)),$(call qstrip,$(CONFIG_CCACHE_DIR)),$(TOPDIR)/.ccache)
  export CCACHE_COMPILERCHECK:=%compiler% -dumpmachine; %compiler% -dumpversion
endif

TARGET_CONFIGURE_OPTS = \
  AR="$(TARGET_AR)" \
  AS="$(TARGET_CC) -c $(TARGET_ASFLAGS)" \
  LD="$(TARGET_LD)" \
  NM="$(TARGET_NM)" \
  CC="$(TARGET_CC)" \
  GCC="$(TARGET_CC)" \
  CXX="$(TARGET_CXX)" \
  RANLIB="$(TARGET_RANLIB)" \
  STRIP=$(TARGET_CROSS)strip \
  OBJCOPY=$(TARGET_CROSS)objcopy \
  OBJDUMP=$(TARGET_CROSS)objdump \
  SIZE=$(TARGET_CROSS)size

DISABLE_IPV6=$(if $(CONFIG_FIRMWARE_ENABLE_IPV6),,--disable-ipv6)
