include $(ROOTDIR)/rules.mk

PKG_NAME:=sqm-qos

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
endef

define Build/Configure
endef

define Build/Compile
endef

$(eval $(call BuildPackage,sqm-qos))

romfs:
	$(CP) ./files/* $(ROMFSDIR)/
